id: rc_smashing
name: Smashing4Summit
author: runcows
description: Arrows and Tridents can break more blocks!

version: 0.0.1

output: out

data_pack:
  load: 
    data: src/data
    data/rc_smashing/modules: src/modules
  min_format: 107
  max_format: 107
  name: smashing_summit_DP
  zipped: false

resource_pack:
  load:
    assets: src/assets
  min_format: 88
  max_format: 88
  name: smashing_summit_RP
  zipped: false

require:
  - plugins.output.clear
  - beet.contrib.model_merging
  - beet.contrib.copy_files
  - bolt
  - bolt_native_macros

pipeline:
  - plugins.write_mcmeta
  - mecha
  # no minify_json, that's handled by plugins.output
  - plugins.output

meta:
  mecha:
    formatting:
      nbt_compact: True
  bolt:
    entrypoint: ["*"]
  copy_files:
    data_pack:
      data/rc_smashing/sync_setting/rc_smashing.json: src/data/rc_smashing/sync_setting/rc_smashing.json
  smashing:
    arrow_smashable: [
      "minecraft:decorated_pot",
      "minecraft:melon",
      "minecraft:pumpkin"
    ]
