on:
  push:
    branches:
      # - main
      - bolt-rewrite
  workflow_dispatch:
env:
  COMMIT_MSG: ${{ github.event.head_commit.message }}
  GH_TOKEN: ${{ github.token }}
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        # comment out this with block later
        with:
          ref: bolt-rewrite
      - name: Set up uv
        uses: astral-sh/setup-uv@v7
      - name: Build Pack & Release
        run: uv run beet build