on:
  push:
    branches:
      # - main
      - bolt-rewrite
  workflow_dispatch:
env:
  COMMIT_MSG: ${{ github.event.head_commit.message }}
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        # comment out this with block later
        with:
          ref: bolt-rewrite
      - name: Load Values From Beet.yaml
        run: |
          VERSION=$(yq '.version' beet.yaml)
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          echo VERSION = $VERSION
          MC_VERSION=$(yq '.minecraft' beet.yaml)
          echo "MC_VERSION=$MC_VERSION" >> $GITHUB_ENV
          echo MC_VERSION = $MC_VERSION
      - name: Set up uv
        uses: astral-sh/setup-uv@v7
      - name: Build Pack
        run: uv run beet build
        env:
          COMMIT_MSG: $COMMIT_MSG
      - name: Create Github Release
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          gh release create v$VERSION \
            --title "v$VERSION" \
            --notes "$COMMIT_MSG" \
            ./out/*.zip
        # --fail-on-no-commits